name: lovely_roommates
description: Lovely Roommates
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.8.4
  velocity_x: ^4.1.1
  go_router: ^10.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  overlay_support: ^2.1.0
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  shimmer_animation: ^2.1.0+1
  extended_image: ^8.0.2
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.3
  freezed_annotation: ^2.4.1
  enum_to_string: ^2.0.1
  sprintf: ^7.0.0
  equatable: ^2.0.5
  dartx: ^1.2.0
  collection: ^1.18.0
  dart_extensions: ^2.2.2
  fast_immutable_collections: ^9.1.5
  awesome_extensions: ^2.0.9
  nb_utils: ^6.0.0
  intl: ^0.18.1
  connectivity_plus: ^4.0.1
  device_info_plus: ^9.0.2
  flutter_svg_provider: ^1.0.4
  flex_color_scheme: ^7.2.0
  font_awesome_flutter: ^10.5.0
  carousel_slider: ^4.2.1
  modal_bottom_sheet: ^3.0.0-pre
  permission_handler: ^10.4.3
  app_settings: ^5.0.0
  badges: ^3.1.1
  expandable: ^5.0.1
  location: ^5.0.1
  fl_chart: ^0.63.0
  flutter_login: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dependency_validator: ^3.2.2
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^5.0.3
  freezed: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  lint: ^2.1.2
  flutter_gen_runner: ^5.3.1
  go_router_builder: ^2.2.4
  build_runner: ^2.4.6

dependency_overrides:
  http: ^1.1.0
  collection: ^1.18.0

flutter_gen:
  output: lib/generated/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      style: dot-delimiter
  fonts:
    enabled: true
    inputs: []
    outputs:
      class_name: Fonts
  colors:
    enable: true
    inputs: []
    outputs:
      class_name: Colors

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icons/logo.png"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icons/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
#    - assets/images/svg/
#    - assets/images/png/
#    - assets/lotties/
#    - assets/rives/
#    - assets/colors/
  fonts: []

